version: '3.8'
 
services:
  pokemon_db:
    image: postgres:16.3
    container_name: db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pokemondbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
volumes:
  pokemondbdata: